credentials:
  usernames:
    Zubairu:
      email: zubairu.ayuba@azubiafrica.org
      logged_in: False # Will be managed automatically
      name: ayzubair
      password: 'Password@azubi' # Make sure to enclose in quotes
    Angel:
      email: 
      logged_in: False # Will be managed automatically
      name: Angel
      password: '123' # Make sure to enclose in quotes
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
